# -*- coding: utf-8 -*-
"""Tweet extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15fieN0sokLJKQLnmgnUryiZYjXhX2M6G
"""

from google.colab import drive
drive.mount('/content/drive')

import tweepy
import pandas as pd
from datetime import datetime, timedelta

# Enter your Twitter API credentials
consumer_key = 'BrlXqPCKhZiK2DZMYhX3vFSjt'
consumer_secret = 'NqLZw4i4BDJCZNoCijqCM4eg1OjTWq09hgXMz9m8ishKRuJiTy'
bearer_token = 'AAAAAAAAAAAAAAAAAAAAABqWlgEAAAAAd7Uw6r6CqpcGmH2fbaohTRKEL4w%3DTEZ35o6tl87nzmLPbpRzBCVO5J7GsPty9lr8Xlk1ymDawR9SjI'

# Authenticate with the Twitter API using OAuth 2.0
auth = tweepy.AppAuthHandler(consumer_key, consumer_secret)
api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

# Define the date range for the tweets
start_date = datetime(2022, 12, 1).date()
end_date = datetime(2023, 1, 31).date()

# Define your query keywords
query_list = ['#ChatGPT', '#BardAI','#Artificial Intelligence','#AI','#BigData','#MachineLearning','#Robotics']

# Define a function to get tweets for a specific date
def get_tweets_by_date(query, date, limit):
    tweets = []
    cursor = tweepy.Cursor(api.search,
                           q=query,
                           lang='en',
                           since_id=date.strftime('%Y-%m-%d'),
                           until=(date + timedelta(days=1)).strftime('%Y-%m-%d'),
                           tweet_mode='extended').items(limit)
    for tweet in cursor:
        tweets.append(tweet)
    return tweets

# Get the tweets and create a dataframe
tweets_list = []
for query in query_list:
    for date in pd.date_range(start=start_date, end=end_date, freq='D'):
        tweets = get_tweets_by_date(query, date, 35)
        for tweet in tweets:
            tweet_dict = {}
            tweet_dict["ID"] = tweet.user.id
            tweet_dict["UserName"] = tweet.user.screen_name
            tweet_dict["Tweets"] = tweet.full_text
            tweet_dict["Date"] = tweet.created_at
            tweet_dict["Source"] = tweet.source
           
            tweets_list.append(tweet_dict)

df = pd.DataFrame(tweets_list, columns=["ID", "UserName", "Tweets", "Date", "Source"])
df

df.to_csv('/content/drive/MyDrive/2.csv',index=False)